baseURL = "https://www.mrfriz.fr/discgolf"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "MrFriz Discgolf Rennes"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true